### ISSUE TITLE
ImportError: No module named Box2D

### ISSUE THREAD

**Issue by bennibaermann** [andrewrk/MonsterMechanics#1]
hi,

i want to try the game but got only some import errors. after installation of pygame-pyglet (should be mentioned in requirements) i still got:

Traceback (most recent call last):
  File "run_game.py", line 3, in <module>
    monstermechanics.**main**.main()
  File "/home/benni/MonsterMechanics/monstermechanics/**main**.py", line 28, in main
    game.start()
  File "/home/benni/MonsterMechanics/monstermechanics/game.py", line 147, in start
    self.world = World()
  File "/home/benni/MonsterMechanics/monstermechanics/world.py", line 10, in **init**
    physics = get_physics()
  File "/home/benni/MonsterMechanics/monstermechanics/physics.py", line 94, in get_physics
    from .box2d_physics import Box2DPhysics
  File "/home/benni/MonsterMechanics/monstermechanics/box2d_physics.py", line 3, in <module>
    from Box2D import *
ImportError: No module named Box2D

setup Python 2.7.6, pyglet 1.1.4, ubuntu 14.04

thanks for any hints!

**Comment by bennibaermann** [comment]
sorry, found it myself allready: "apt-get install python-box2d" solved it.
